version: 5.1-{branch}+{build}

image: 
  - Visual Studio 2019
  - macos-mojave
  - Ubuntu

environment:
  MSYSTEM: MINGW64
  matrix:
    - WITH_DEBUG_SYMBOLS: false
    - WITH_DEBUG_SYMBOLS: true

for:
-
  branches:
    except:
      - master
  matrix:
    exclude:
      - image: Visual Studio 2019
        WITH_DEBUG_SYMBOLS: false
      - image: Ubuntu
        WITH_DEBUG_SYMBOLS: false
      - image: macos-mojave
        WITH_DEBUG_SYMBOLS: false
-
  branches:
    only:
      - master
  matrix:
    exclude:
      - image: Ubuntu
        WITH_DEBUG_SYMBOLS: true
      - image: macos-mojave
        WITH_DEBUG_SYMBOLS: true
-
  matrix:
    only:
      - image: Ubuntu
  services:
    - docker
  install:
    - docker pull knossostool/knossos
-
  matrix:
    only:
      - image: macos-mojave
  environment:
    MACOSX_DEPLOYMENT_TARGET: 10.13
  install:
    - time brew update && time brew upgrade
    - time brew remove qt6 || true
    - time brew install boost ninja python qt5 quazip snappy
    - sh ci/build_macos_PythonQt.sh
  build_script:
    - sh ci/build_macos.sh

build_script:
  - cmd: C:\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
  - cmd: C:\msys64\usr\bin\bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci/build_windows.sh"
  - sh: docker run --privileged --cap-add=ALL -v /lib/modules:/lib/modules -v /dev:/dev -v ${APPVEYOR_BUILD_FOLDER}:/root/knossos -e APPVEYOR_REPO_BRANCH knossostool/knossos bash -c '/root/knossos/ci/build_linux.sh'

artifacts:
  - path: '*nightly.*'

deploy:
  - provider: GitHub
    tag: nightly
    auth_token:
      secure: 9tKkhsqR9qSoKt3390923aZ0EauffZQQ/6Ho0HdYlTEudtFJ1eTnw6B3TGclgqA0 # your encrypted token from GitHub
    artifact: /.*\.KNOSSOS\..*/
    prerelease: true
    force_update: true
    on:
      branch: master
      WITH_DEBUG_SYMBOLS: false
  - provider: GitHub
    tag: nightly-dev
    auth_token:
      secure: 9tKkhsqR9qSoKt3390923aZ0EauffZQQ/6Ho0HdYlTEudtFJ1eTnw6B3TGclgqA0 # your encrypted token from GitHub
    artifact: /.*-KNOSSOS\..*/
    prerelease: true
    force_update: true
    on:
      WITH_DEBUG_SYMBOLS: true